#!/usr/bin/env python3

import os
import numpy as np
import pandas as pd
from matplotlib import pylab as plt
import mpl_scatter_density
from matplotlib import colors
import cv2
import argparse

import warnings
warnings.filterwarnings("ignore")


def estBound_tifBins(fstBCpos_sndBC: str, odir: str, bins: int = 100):
    """This script is to
    1. make plot to estimate tissue boundary
    2. make bins and save as tif file for the following manually circle tissue boundary

    Params:
      fstBCpos_sndBC: 4 columns: barcode, x, y and ChipZone, can be generated by ChipZone_whitelist.py.
      odir: output dir, will be created if it not exists.
      bins: int indicating how many pixels the output img will be clustered.

    Return: None
    """

    # creat output dir
    os.system(f"mkdir -p {odir}")

    # read file fstBCpos_BCs2nd
    df = pd.read_csv(fstBCpos_sndBC, sep="\t", header=None, usecols=[0, 1, 2])
    df.columns = ["BC", "x", "y"]
    df.set_index("BC", inplace=True)
    df = df.astype("float64")

    # min and max of x and y
    xmin = float(min(df["x"]))  # 0.0
    xmax = float(max(df["x"]))  # 224639.0
    ymin = float(min(df["y"]))  # 1.0
    ymax = float(max(df["y"]))  # 43007.8

    # ------------- plot using mpl_scatter_density for boundary estimating ------------- #
    # figure setup
    fig = plt.figure(figsize=(16, 5))
    ax = fig.add_subplot(1, 1, 1, projection="scatter_density")

    # color
    clist = [(0, "#ffffff"), (1e-20, "#440053"), (0.5, "#2a788e"), (1, "#fde624")]
    #clist=['white', 'pink', 'red','darkred'] # 元组列表(值，颜色)
    cmp = colors.LinearSegmentedColormap.from_list("color", clist, N=pow(2, 16))

    # plot
    density = ax.scatter_density(df["x"], df["y"], cmap=cmp)
    ax.set_ylim(ymax, ymin)
    fig.colorbar(density, label="Number of points per pixel", orientation="horizontal")
    plt.gca().set_aspect("equal", adjustable="box")

    plt.savefig(f"{odir}/tissue_boundary_density_viridis.png", dpi=2000)
    # plt.savefig(f"{odir}/tissue_boundary_density_viridis.tif", dpi=1200)

    plt.show()

    # ------------------ tif for manually plot the tissue boundary ------------------ #
    # make bins
    dat = pd.DataFrame()
    dat["bins(x-xmin)"] = round((df["x"] - xmin) / bins).astype(int)
    dat["bins(y-ymin)"] = round((df["y"] - ymin) / bins).astype(int)

    # max of x and y after binning
    xmax = max(dat["bins(x-xmin)"]) + 1
    ymax = max(dat["bins(y-ymin)"]) + 1
    heatmap = np.zeros((ymax, xmax))

    # heatmap
    for n in range(len(dat)):
        coordTemp = dat.iloc[n, ]
        heatmap[coordTemp[1]][coordTemp[0]] += 1

    # xx
    max_value = np.max(heatmap)
    if max_value >= 65534:
        heatmap = heatmap * (65534 - 1) / max_value
    heatmap[-1][-1] = min(max_value + 1, 65535)

    # write as tif
    cv2.imwrite(
        f"{odir}/bins{bins}_xmin{int(xmin)}_ymin{int(ymin)}.tif",
        np.array(heatmap).astype(np.uint16),
    )


if __name__ == "__main__":
    description = "This script is to (1) make plot to estimate tissue boundary and (2) make bins and save as tif file for the following manually circle tissue boundary."
    parser = argparse.ArgumentParser(
        description=description, formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    parser.add_argument(
        "-f",
        "--fstBCpos_sndBC",
        default=None,
        help="4 columns: barcode, x, y and ChipZone, can be generated by ChipZone_whitelist.py.",
    )
    parser.add_argument(
        "-o",
        "--odir",
        default=None,
        help="output dir, will be created if it not exists.",
    )
    parser.add_argument(
        "-b",
        "--bins",
        type=int,
        default=100,
        help="int indicating how many pixels will be clustered.",
    )
    args = parser.parse_args()
    estBound_tifBins(args.fstBCpos_sndBC, args.odir, args.bins)
